gateways:
  omrs:
    connection:
      type: mysql
      host: localhost
      port: 3306
      user: root
      password: openmrs
#      database: openmrs
  omopp:
    connection:
      type: postgres
      host: localhost
      port: 5432
      user: omop
      password: omop
      database: omop

default_gateway: omrs

model_defaults:
  dialect: mysql
