version: '3.8'

services:
  # dbname: openmrs username: openmrs pw: openmrs rootpw: openmrs
  omrsdb:
    image: openmrs/openmrs-reference-application-3-db:nightly-with-data
    ports:
      - "3306:3306"
  sqlmesh-db:
    image: mariadb:10.11.7
    restart: "unless-stopped"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: openmrs
      MYSQL_ROOT_PASSWORD: openmrs
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  sqlmesh:
    build: .
    container_name: sqlmesh
    environment:
      SRC_HOST: omrsdb
      SRC_PORT: 3306
      SRC_USER: openmrs
      SRC_PASS: openmrs
      SRC_DB: openmrs
    depends_on:
      - sqlmesh-db
      - omrsdb
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["bash", "./entrypoint.sh"]

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: omop
      POSTGRES_USER: omop
      POSTGRES_PASSWORD: omop
    ports:
      - "5432:5432"
    volumes:
      - ./omop-ddl/processed/ddl:/docker-entrypoint-initdb.d

volumes:
  db-data: ~
  postgres_data: ~
